name: windows

inputs:
  config-preset:
    required: true
  build-preset:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure PartStacker
      run: |
        cmake --preset ${{ inputs.config-preset }} -G "Visual Studio 17 2022" -A x64
      shell: powershell

    - name: Build PartStacker
      run: |
        cmake --build --preset ${{ inputs.build-preset }} -j8
      shell: powershell
