on:
  workflow_dispatch:

jobs:

  build-macos:
    runs-on: macos-15
    strategy:
      matrix:
        include:
          # - triplet: x64-osx
          #   arch: x86_64
          - triplet: arm64-osx
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure and build x64
        uses: ./.github/actions/common-macos
        with:
          config-preset: Release
          build-preset: Release
          vcpkg-triplet: ${{ matrix.triplet }}
          arch: ${{ matrix.arch }}

      - run: |
          cd build
          echo "###### build"
          ls
          cd vcpkg_installed
          echo "###### vcpkg_installed"
          ls
          cd arm64-osx
          echo "###### arm64-osx"
          ls
          cd include
          echo "###### include"
          ls
          cd wx-3.2
          echo "###### wx-3.2"
          ls
          cd osx
          echo "###### osx"
          ls

      # - run: |
      #     cd external/vcpkg
      #     ls
      #     echo "......"
      #     cd buildtrees
      #     ls
      #     echo "......"
      #     cd wxwidgets
      #     ls
      #     echo "......"
      #     cd src
      #     ls
      #     echo "......"
      #     cd v3.2.7-90467b189b.clean
      #     ls
      #     echo "......"
      #     cd include
      #     ls
      #     echo "......"
      #     cd wx
      #     ls
      #     echo "......"
      #     cd osx
      #     ls
