on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  build-windows:
    needs: run-tests
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - uses: ./.github/actions/common-windows
        with:
          config-preset: Release
          build-preset: Release

      - name: Copy exe
        run: copy ".\bin\Release\PartStackerGUI.exe" ".\bin\Release\PartStackerGUI-windows.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PartStackerGUI-windows
          path: .\bin\Release\PartStackerGUI-windows.exe

  build-macos:
    needs: run-tests
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - uses: ./.github/actions/common-macos
        with:
          config-preset: Release
          build-preset: Release

      - name: Package into DMG
        run: |
          mkdir -p ./bin/Release/dmg-root
          mv ./bin/Release/PartStackerGUI.app ./bin/Release/dmg-root/
          hdiutil create \
            -volname "PartStackerGUI" \
            -srcfolder ./bin/Release/dmg-root \
            -format UDZO \
            ./bin/Release/PartStackerGUI-mac.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PartStackerGUI-mac
          path: ./bin/Release/PartStackerGUI-mac.dmg
