on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2025

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure PartStacker
        run: |
          cmake --preset Release -G "Visual Studio 17 2022" -A x64

      - name: Build PartStacker
        run: |
          cmake --build --preset Release -j8
          copy ".\bin\Release\PartStackerGUI.exe" ".\bin\Release\PartStackerGUI-windows.exe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PartStackerGUI-windows
          path: .\bin\Release\PartStackerGUI-windows.exe

  macos:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_16.3.app

      - name: Configure PartStacker
        run: |
          cmake --preset Release \
                -G Xcode \
                -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
                -DCMAKE_OSX_DEPLOYMENT_TARGET=11.6

      - name: Build PartStacker
        run: cmake --build --preset Release -j8

      - name: Package into DMG
        run: |
          mkdir -p ./bin/Release/dmg-root
          mv ./bin/Release/PartStackerGUI.app ./bin/Release/dmg-root/
          hdiutil create \
            -volname "PartStackerGUI" \
            -srcfolder ./bin/Release/dmg-root \
            -format UDZO \
            ./bin/Release/PartStackerGUI-mac.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PartStackerGUI-mac
          path: ./bin/Release/PartStackerGUI-mac.dmg
