on:
  workflow_dispatch:

jobs:

  build-macos:
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - triplet: x64-osx
            arch: x86_64
          - triplet: arm64-osx
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure and build x64
        uses: ./.github/actions/common-macos
        with:
          config-preset: Release
          build-preset: Release
          vcpkg-triplet: ${{ matrix.triplet }}
          arch: ${{ matrix.arch }}
