on:
  workflow_dispatch:
  workflow_call:

jobs:
  test-windows:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Caching
        uses: ./.github/actions/caching
        with:
          key-prefix: windows-build

      - name: Configure and build
        uses: ./.github/actions/common-windows
        with:
          config-preset: Debug
          build-preset: Tests

      - name: Run Tests
        run: |
          cd ./build/
          ctest

  test-macos:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Caching
        uses: ./.github/actions/caching
        with:
          key-prefix: macos-build

      - name: Configure and build
        uses: ./.github/actions/common-macos
        with:
          config-preset: Debug
          build-preset: Tests
          vcpkg-triplet: arm64-osx
          arch: arm64

      - name: Run Tests
        run: |
          cd ./build/
          ctest
